version: '3'
services:
  app1:
    image: nginx:latest
    volumes:
      - ./server1:/usr/share/nginx/html
    expose:
      - 80
    networks:
      - nginx_local

  app2:
    image: nginx:latest
    volumes:
      - ./server2:/usr/share/nginx/html
    expose:
      - 80
    networks:
      - nginx_local

  app3:
    image: nginx:latest
    volumes:
      - ./server3:/usr/share/nginx/html
    expose:
      - 80
    networks:
      - nginx_local
    
  reverse-proxy:
    restart: always
    build: reverse-proxy
    ports:
      - 80:80
    networks:
      - nginx_local
    
networks:
  nginx_local:
    driver: bridge